services:
    rokol:
        build:
            context: ./docker/8.1fpm
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        container_name: "${PHP_CONTAINER_NAME:-rokol}"
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        depends_on:
            - mysql
            - redis
#        command: ['chmod', '-R', '777', './']
    mysql:
        image: 'mysql/mysql-server:8.0'
        container_name: rokol_mysql
        ports:
            - '${DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'sail-mysql:/var/lib/mysql'
            - './docker/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
#        command: ['rm', '/var/lib/mysql/mysql.sock.lock']
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD}'
            retries: 3
            timeout: 5s


    nginx:
        container_name: rokol_nginx
        build:
            context: "./docker/nginx"
            dockerfile: Dockerfile
            args:
                NGINX_PHP_UPSTREAM_CONTAINER: "${PHP_CONTAINER_NAME:-rokol}"
                NGINX_PHP_UPSTREAM_PORT: "${NGINX_PHP_UPSTREAM_PORT:-9000}"
                NGINX_HOST_HTTP_PORT: "${NGINX_HOST_HTTP_PORT:-80}"
                NGINX_DOCKER_INTERNAL_HOST_HTTP_PORT: "${NGINX_DOCKER_INTERNAL_HOST_HTTP_PORT:-80}"
                NGINX_HOST_HTTPS_PORT: "${NGINX_HOST_HTTPS_PORT:-443}"
                NGINX_DOCKER_INTERNAL_HOST_HTTPS_PORT: "${NGINX_DOCKER_INTERNAL_HOST_HTTPS_PORT:-443}"
                NGINX_SERVER_NAME: "${NGINX_SERVER_NAME:-rokol.test}"
        volumes:
            #      - ${NGINX_SSL_PATH}:/etc/nginx/ssl
            - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
            - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
#            - ${NGINX_SITES_PATH}:/etc/nginx/sites-enabled
        ports:
            - "${NGINX_HOST_HTTP_PORT:-80}:${NGINX_DOCKER_INTERNAL_HOST_HTTP_PORT:-80}"
            - "${NGINX_HOST_HTTPS_PORT:-443}:${NGINX_DOCKER_INTERNAL_HOST_HTTPS_PORT:-443}"
        networks:
            - sail
        depends_on:
            - rokol


    redis:
        image: 'redis:alpine'
        ports:
            - '6379:6379'
        volumes:
            - 'sail-redis:/data'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - redis-cli
                - ping
            retries: 3
            timeout: 5s

    phpmyadmin:
        depends_on:
            - mysql
        image: phpmyadmin:apache
        restart: always
        ports:
            - "8090:80"
        environment:
            PMA_HOST: '${DB_HOST:-mysql}'
            PMA_PORT: '${DB_PORT:-3306}'
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            UPLOAD_LIMIT: 10G
            MAX_EXECUTION_TIME: 3600
            PMA_PMADB: pmadb
            PMA_CONTROLUSER: '${DB_USERNAME}'
            PMA_CONTROLPASS: '${DB_PASSWORD}'
            PMA_QUERYHISTORYDB: true
            MEMORY_LIMIT: 1G
        networks:
            - sail

networks:
    sail:
        driver: bridge
volumes:
    sail-mysql:
        driver: local
    sail-redis:
        driver: local
